<script lang="ts">
  import { api, type RequestDetail, type RequestStatus, type RequestSummary } from '../../lib/api'
  import ErrorState from '../../lib/components/ErrorState.svelte'
  import LoadingState from '../../lib/components/LoadingState.svelte'
	import { handleRenderedContentClick } from '../../lib/nav'
  interface Props { project:string; id:string|null; reloadKey:number; navigate:(path:string)=>void }
  let {project,id,reloadKey,navigate}:Props=$props(); let items=$state<RequestSummary[]>([]),detail=$state<RequestDetail|null>(null),loading=$state(true),error=$state(''),q=$state(''),status=$state<RequestStatus|''>(''),terminal=$state(false)
	$effect(()=>{project;id;reloadKey;q;status;terminal;let cancelled=false;loading=true;error='';(id?api.getRequest(id):api.listRequests(project,{q,status:status||undefined,terminal})).then(v=>{if(cancelled)return;if(id)detail=v as RequestDetail;else items=v as RequestSummary[]}).catch(e=>{if(!cancelled)error=e instanceof Error?e.message:'Could not load requests'}).finally(()=>{if(!cancelled)loading=false});return()=>{cancelled=true}})
</script>
{#if loading}<LoadingState label="Loading requests…" message="Fetching requests from the hub." />
{:else if error}<ErrorState title="Could not load requests" message={error}/>
{:else if detail}<article><p class="muted">{detail.project} · {detail.status} · P{detail.priority}</p><h2>{detail.title}</h2>{#if detail.requested_by}<p>Requested by {detail.requested_by}</p>{/if}<!-- svelte-ignore a11y_click_events_have_key_events --><!-- svelte-ignore a11y_no_static_element_interactions --><div class="markdown" onclick={(event)=>handleRenderedContentClick(event,navigate)}>{@html detail.html}</div><h3>Linked issues</h3><ul>{#each detail.issues as linked}<li>{#if linked.missing}{linked.id} (missing){:else}<a href={'/issues/'+encodeURIComponent(linked.id)} onclick={(e)=>{e.preventDefault();navigate('/issues/'+encodeURIComponent(linked.id))}}>{linked.id}</a> — {linked.status} · {linked.title}{/if}</li>{:else}<li>No linked issues.</li>{/each}</ul>{#if detail.backlinks.length}<h3>Backlinks</h3><ul>{#each detail.backlinks as link}<li>{link.title ?? link.from}</li>{/each}</ul>{/if}{#if detail.log.length}<h3>Log</h3><ul>{#each detail.log as entry}<li>{entry.event}</li>{/each}</ul>{/if}{#if detail.toc.length}<nav aria-label="Table of contents">{#each detail.toc as entry}<a href={'#'+entry.id}>{entry.text}</a>{/each}</nav>{/if}</article>
{:else}<section><label>Search <input bind:value={q} placeholder="title, id, label, requester, or body" /></label><label>Status <select bind:value={status}><option value="">Open requests</option><option value="open">Open</option><option value="accepted">Accepted</option><option value="in_progress">In progress</option><option value="resolved">Resolved</option><option value="declined">Declined</option></select></label><label><input type="checkbox" bind:checked={terminal}/> Include terminal</label><div class="cards">{#each items as item}<a class="card" href={'/requests/'+encodeURIComponent(item.id)} onclick={(e)=>{e.preventDefault();navigate('/requests/'+encodeURIComponent(item.id))}}><strong>{item.title}</strong><span>{item.id} · {item.status} · P{item.priority} · {item.project} · {item.issue_count} linked issues</span>{#if item.requested_by}<span>Requested by {item.requested_by}</span>{/if}{#if item.labels.length}<span>{item.labels.join(', ')}</span>{/if}<small>Updated {item.updated}</small></a>{:else}<p class="muted">No requests found.</p>{/each}</div></section>{/if}
<style>.cards{display:grid;gap:10px;margin-top:16px}.card{display:grid;gap:4px;padding:12px;border:1px solid var(--border,#ddd);border-radius:8px}.markdown{margin:20px 0}</style>
