package schema

import (
	"context"
	"database/sql"
	"embed"
	"fmt"
	"io/fs"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/pressly/goose/v3"
	"github.com/pressly/goose/v3/lock"
)

//go:embed migrations/*/*.sql
var migrationsFS embed.FS

const migrationsDir = "migrations"

// migrateAdvisoryLockID is a stable int64 for pg_advisory_lock.
const migrateAdvisoryLockID int64 = 0x626e74726b72 // "bntrkr"

const (
	migrationVersionTable = "bn_schema_versions"
	migrationLockName     = "beans_schema_migrations"
)

var migrationFilenameRE = regexp.MustCompile(`^([0-9]{4,})_([A-Za-z0-9][A-Za-z0-9_\-]*)\.sql$`)

// Driver is the database dialect used for schema migrations.
type Driver string

const (
	DriverPostgres Driver = "postgres"
	DriverMySQL    Driver = "mysql"
	DriverSQLite   Driver = "sqlite"
)

// Migration is one parsed entry from the embedded migrations directory.
type Migration struct {
	Version int
	Name    string
	SQL     string
}

// Migrations returns the embedded migration filesystem.
func Migrations() embed.FS {
	return migrationsFS
}

// MigrationFS returns the embedded migration filesystem rooted at the driver's directory.
func MigrationFS(driver Driver) (fs.FS, error) {
	dir, err := migrationsPath(driver)
	if err != nil {
		return nil, err
	}
	migrations, err := fs.Sub(migrationsFS, dir)
	if err != nil {
		return nil, fmt.Errorf("schema: migrations fs for %s (%s): %w", driver, dir, err)
	}
	return migrations, nil
}

// ListMigrations returns every embedded migration for driver sorted ascending by Version.
func ListMigrations(driver Driver) ([]Migration, error) {
	dir, err := migrationsPath(driver)
	if err != nil {
		return nil, err
	}
	entries, err := fs.ReadDir(migrationsFS, dir)
	if err != nil {
		return nil, fmt.Errorf("schema: read migrations dir for %s (%s): %w", driver, dir, err)
	}

	out := make([]Migration, 0, len(entries))
	seen := make(map[int]string, len(entries))
	for _, ent := range entries {
		if ent.IsDir() {
			continue
		}
		name := ent.Name()
		if !strings.HasSuffix(name, ".sql") {
			continue
		}
		matches := migrationFilenameRE.FindStringSubmatch(name)
		if matches == nil {
			return nil, fmt.Errorf("schema: migration %q does not match NNNN_name.sql", name)
		}
		version, err := strconv.Atoi(matches[1])
		if err != nil {
			return nil, fmt.Errorf("schema: parse version in %q: %w", name, err)
		}
		if existing, ok := seen[version]; ok {
			return nil, fmt.Errorf("schema: duplicate migration version %d (%q and %q)", version, existing, name)
		}
		seen[version] = name

		body, err := fs.ReadFile(migrationsFS, dir+"/"+name)
		if err != nil {
			return nil, fmt.Errorf("schema: read %q: %w", name, err)
		}
		out = append(out, Migration{
			Version: version,
			Name:    matches[2],
			SQL:     string(body),
		})
	}

	sort.Slice(out, func(i, j int) bool { return out[i].Version < out[j].Version })
	return out, nil
}

// Migrate applies all embedded bn migrations using goose's library API.
func Migrate(ctx context.Context, db *sql.DB, driver Driver) error {
	if db == nil {
		return fmt.Errorf("schema: migrate: nil db")
	}

	migrations, err := MigrationFS(driver)
	if err != nil {
		return err
	}

	dialect, err := gooseDialect(driver)
	if err != nil {
		return err
	}
	opts := []goose.ProviderOption{goose.WithTableName(migrationVersionTable)}
	locker, err := migrationLocker(driver)
	if err != nil {
		return err
	}
	if locker != nil {
		opts = append(opts, goose.WithSessionLocker(locker))
	}
	if err := bootstrapMigrationVersionTable(ctx, db, driver, locker); err != nil {
		return err
	}

	provider, err := goose.NewProvider(
		dialect,
		db,
		migrations,
		opts...,
	)
	if err != nil {
		return fmt.Errorf("schema: goose provider for %s: %w", driver, err)
	}
	if _, err := provider.Up(ctx); err != nil {
		return fmt.Errorf("schema: migrate up for %s: %w", driver, err)
	}
	return nil
}

func bootstrapMigrationVersionTable(ctx context.Context, db *sql.DB, driver Driver, locker lock.SessionLocker) error {
	switch driver {
	case DriverPostgres:
		conn, err := db.Conn(ctx)
		if err != nil {
			return fmt.Errorf("schema: bootstrap postgres migration conn: %w", err)
		}
		defer conn.Close()
		if locker != nil {
			if err := locker.SessionLock(ctx, conn); err != nil {
				return fmt.Errorf("schema: bootstrap postgres migration lock: %w", err)
			}
			defer locker.SessionUnlock(context.WithoutCancel(ctx), conn)
		}
		if _, err := conn.ExecContext(ctx, `
CREATE TABLE IF NOT EXISTS bn_schema_versions (
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	version_id bigint NOT NULL,
	is_applied boolean NOT NULL,
	tstamp timestamp NOT NULL DEFAULT now()
)`); err != nil {
			return fmt.Errorf("schema: create postgres migration version table: %w", err)
		}
		if _, err := conn.ExecContext(ctx, `
INSERT INTO bn_schema_versions (version_id, is_applied)
SELECT 0, true
WHERE NOT EXISTS (
	SELECT 1
	FROM bn_schema_versions
	WHERE version_id = 0
	  AND is_applied = true
)`); err != nil {
			return fmt.Errorf("schema: seed postgres migration zero version: %w", err)
		}
		if _, err := conn.ExecContext(ctx, `
DO $$
BEGIN
	IF to_regclass('goose_db_version') IS NOT NULL THEN
		INSERT INTO bn_schema_versions (version_id, is_applied, tstamp)
		SELECT old.version_id, old.is_applied, old.tstamp
		FROM goose_db_version old
		WHERE old.is_applied = true
		  AND NOT EXISTS (
			SELECT 1
			FROM bn_schema_versions new
			WHERE new.version_id = old.version_id
			  AND new.is_applied = old.is_applied
		  );
	END IF;
END $$`); err != nil {
			return fmt.Errorf("schema: bootstrap postgres migration versions: %w", err)
		}
		return nil
	case DriverMySQL:
		return nil
	case DriverSQLite:
		return nil
	default:
		return fmt.Errorf("schema: unsupported migration bootstrap driver %q", driver)
	}
}

func migrationsPath(driver Driver) (string, error) {
	switch driver {
	case DriverPostgres:
		return migrationsDir + "/postgres", nil
	case DriverMySQL:
		return migrationsDir + "/mysql", nil
	case DriverSQLite:
		return migrationsDir + "/sqlite", nil
	default:
		return "", fmt.Errorf("schema: unsupported migration driver %q", driver)
	}
}

func gooseDialect(driver Driver) (goose.Dialect, error) {
	switch driver {
	case DriverPostgres:
		return goose.DialectPostgres, nil
	case DriverMySQL:
		return goose.DialectMySQL, nil
	case DriverSQLite:
		return goose.DialectSQLite3, nil
	default:
		return "", fmt.Errorf("schema: unsupported goose driver %q", driver)
	}
}

func migrationLocker(driver Driver) (lock.SessionLocker, error) {
	switch driver {
	case DriverPostgres:
		locker, err := lock.NewPostgresSessionLocker(lock.WithLockID(migrateAdvisoryLockID))
		if err != nil {
			return nil, fmt.Errorf("schema: postgres session locker: %w", err)
		}
		return locker, nil
	case DriverMySQL:
		return mysqlSessionLocker{name: migrationLockName, timeoutSeconds: 60}, nil
	case DriverSQLite:
		return nil, nil
	default:
		return nil, fmt.Errorf("schema: unsupported migration lock driver %q", driver)
	}
}

type mysqlSessionLocker struct {
	name           string
	timeoutSeconds int
}

func (l mysqlSessionLocker) SessionLock(ctx context.Context, conn *sql.Conn) error {
	var locked sql.NullInt64
	if err := conn.QueryRowContext(ctx, "SELECT GET_LOCK(?, ?)", l.name, l.timeoutSeconds).Scan(&locked); err != nil {
		return fmt.Errorf("schema: mysql get migration lock: %w", err)
	}
	if !locked.Valid {
		return fmt.Errorf("schema: mysql get migration lock returned NULL")
	}
	if locked.Int64 != 1 {
		return fmt.Errorf("schema: mysql migration lock timed out")
	}
	return nil
}

func (l mysqlSessionLocker) SessionUnlock(ctx context.Context, conn *sql.Conn) error {
	var unlocked sql.NullInt64
	if err := conn.QueryRowContext(ctx, "SELECT RELEASE_LOCK(?)", l.name).Scan(&unlocked); err != nil {
		return fmt.Errorf("schema: mysql release migration lock: %w", err)
	}
	if !unlocked.Valid {
		return fmt.Errorf("schema: mysql release migration lock returned NULL")
	}
	if unlocked.Int64 != 1 {
		return fmt.Errorf("schema: mysql migration lock was not held")
	}
	return nil
}
