-- 0004_bn_repos.sql
--
-- Repository registry foundation for multi-repo workspace routing. These
-- tables stay in the bn_ namespace because repo onboarding and issue routing
-- are authored through the bn tracker surface.
--
-- Per project policy: no IF NOT EXISTS — the runner owns "should this run?"
-- via bn_schema_versions + a session advisory lock.

-- +goose Up
-- +goose StatementBegin

-- ---------------------------------------------------------------------------
-- bn_repos
-- ---------------------------------------------------------------------------
-- One row per onboarded repository within a project prefix. id is generated by
-- the Go layer (repo-<hex>) to avoid adding a Postgres extension dependency for
-- UUID defaults.

CREATE TABLE bn_repos (
    id              TEXT        PRIMARY KEY,
    prefix          TEXT        NOT NULL REFERENCES bn_projects(prefix) ON DELETE CASCADE,
    slug            TEXT        NOT NULL,
    display_name    TEXT        NOT NULL,
    remote_url      TEXT        NOT NULL,
    default_branch  TEXT        NOT NULL DEFAULT 'main',
    worktree_subdir TEXT        NOT NULL DEFAULT '',
    clone_strategy  TEXT        NOT NULL DEFAULT 'mirror-cache',
    auth_ref        TEXT        NOT NULL,
    enabled         BOOLEAN     NOT NULL DEFAULT true,
    metadata        JSONB       NOT NULL DEFAULT '{}',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by      TEXT        NOT NULL DEFAULT '',
    updated_by      TEXT        NOT NULL DEFAULT '',
    UNIQUE(prefix, slug),
    CHECK (slug ~ '^[a-z0-9][a-z0-9._-]*$'),
    CHECK (display_name <> ''),
    CHECK (remote_url <> ''),
    CHECK (default_branch <> ''),
    CHECK (clone_strategy <> ''),
    CHECK (auth_ref <> ''),
    CHECK (worktree_subdir = '' OR (worktree_subdir !~ '^/' AND worktree_subdir !~ '(^|/)\.\.(/|$)'))
);

CREATE INDEX bn_repos_prefix_enabled_idx ON bn_repos (prefix, enabled, slug);

-- ---------------------------------------------------------------------------
-- bn_repo_aliases
-- ---------------------------------------------------------------------------
-- Extra lookup names for a repo, e.g. clckr, birbparty/clckr, or a forge URL
-- shape. Alias values are project-scoped.

CREATE TABLE bn_repo_aliases (
    prefix     TEXT        NOT NULL REFERENCES bn_projects(prefix) ON DELETE CASCADE,
    alias      TEXT        NOT NULL,
    repo_id    TEXT        NOT NULL REFERENCES bn_repos(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY(prefix, alias),
    CHECK (alias <> '')
);

CREATE INDEX bn_repo_aliases_repo_idx ON bn_repo_aliases (repo_id);

-- ---------------------------------------------------------------------------
-- bn_project_admins
-- ---------------------------------------------------------------------------
-- Repo registry mutation is an administrative operation. Bootstrap is handled
-- by the CLI/store with an explicit no-existing-admin guard.

CREATE TABLE bn_project_admins (
    prefix     TEXT        NOT NULL REFERENCES bn_projects(prefix) ON DELETE CASCADE,
    actor      TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY(prefix, actor),
    CHECK (actor <> '')
);

-- ---------------------------------------------------------------------------
-- bn_repo_audit
-- ---------------------------------------------------------------------------
-- Redacted audit stream for repo registry changes. old_values/new_values are
-- intentionally JSONB so callers can record only fields touched by the command.

CREATE TABLE bn_repo_audit (
    id         BIGSERIAL   PRIMARY KEY,
    prefix     TEXT        NOT NULL REFERENCES bn_projects(prefix) ON DELETE CASCADE,
    repo_id    TEXT        REFERENCES bn_repos(id) ON DELETE SET NULL,
    action     TEXT        NOT NULL,
    actor      TEXT        NOT NULL,
    old_values JSONB       NOT NULL DEFAULT '{}',
    new_values JSONB       NOT NULL DEFAULT '{}',
    command    TEXT        NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (action <> ''),
    CHECK (actor <> '')
);

CREATE INDEX bn_repo_audit_prefix_created_idx ON bn_repo_audit (prefix, created_at DESC);
CREATE INDEX bn_repo_audit_repo_created_idx ON bn_repo_audit (repo_id, created_at DESC);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

DROP TABLE bn_repo_audit;
DROP TABLE bn_project_admins;
DROP TABLE bn_repo_aliases;
DROP TABLE bn_repos;

-- +goose StatementEnd
